import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { Geologica } from "next/font/google";
import Container from "@/components/Container";

export const metadata = {
  title: "Jeremi Boracki",
  description: "Generated by create next app",
};

const geologica = Geologica({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className={`bg-primary text-white ${geologica.className}`}>
        <Navbar />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
